spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/user/**

            - id: auth-jwks
              uri: http://localhost:8083
              predicates:
                - Path=/.well-known/jwks.json

            - id: auction-service
              uri: http://localhost:8080 #Не забыть переписать на имя контейнера в докере
              predicates:
                - Path=/auction/**

            - id: bid-service
              uri: http://localhost:8081 #Не забыть переписать на имя контейнера в докере
              predicates:
                - Path=/bid/**

server:
  port: 8086

