openapi: 3.0.3
info:
  title: Auction API
  version: 1.0.0
  description: |
    Auction API предоставляет функционал для создания и управления аукционами. 
    Возможности:
    - Создание публичных и приватных аукционов
    - Получение информации о конкретных аукционах
    
    Все эндпоинты требуют заголовок `Authorization: Bearer <token>`, 
    за исключением случаев, когда явно указано иное.

tags:
  - name: Auctions
    description: Методы для работы с аукционами (создание, получение информации)

security:
  - bearerAuth: []

paths:
  /auction:
    post:
      tags:
        - Auctions
      summary: Создать новый аукцион
      description: Создаёт новый аукцион с указанной информацией. Все поля обязательны, кроме тех, что явно указаны как необязательные.
      operationId: createAuction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuction'
      responses:
        '201':
          description: Аукцион успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedAuction'
              examples:
                withPassword:
                  summary: Аукцион приватный
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    password: "a1b2c3d4-e5f6-7890-1234-56789abcdef0"
                withoutPassword:
                  summary: Аукцион публичный
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174001"
                    password: null
        '400':
          description: Ошибка валидации запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                invalidArguments:
                  summary: Некорректные аргументы
                  value:
                    status: 400
                    error: "Invalid arguments"
                    message: "startPrice must be positive"
                    path: "/auction"
                    timestamp: "2025-08-30T14:30:00Z"
                validationError:
                  summary: Ошибка валидации DTO
                  value:
                    status: 400
                    error: "Validation error"
                    message: "title: must not be blank; endDate: must be after startDate"
                    path: "/auction"
                    timestamp: "2025-08-30T14:30:01Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auction/{id}:
    get:
      tags:
        - Auctions
      summary: Получить информацию о конкретном аукционе
      description: |
        Возвращает детальную информацию о выбранном аукционе.  
        Можно запросить только необходимые поля, указав их в параметре **fields**.  
        
        - Если `fields` не передан, по умолчанию возвращаются поля:  
          `currency, startDate, startPrice, description, bidIncrement, reservePrice, status, endDate, isPrivate, title, id`.  
        - Чтобы получить дополнительные поля (`allowedUsersCount`, `ownerName`), их нужно явно указать в `fields`.  
        - Поле **allowedUsersCount** доступно только для приватных аукционов.
      operationId: auctionInfo
      parameters:
        - name: id
          in: path
          description: Уникальный идентификатор аукциона
          required: true
          schema:
            type: string
            format: uuid
        - name: password
          in: query
          description: Пароль от аукциона, указывается для приватных аукционов
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: |
            Список полей, которые необходимо вернуть.  
            Возможные значения:  
            `currency, startDate, startPrice, description, bidIncrement, reservePrice, status, endDate, isPrivate, title, id, allowedUsersCount, ownerName`
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - currency
                - startDate
                - startPrice
                - description
                - bidIncrement
                - reservePrice
                - status
                - endDate
                - isPrivate
                - title
                - id
                - allowedUsersCount
                - ownerName
      responses:
        '200':
          description: Успешный ответ с динамическим набором полей
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    additionalProperties: true
              examples:
                default:
                  summary: Ответ по умолчанию (если fields не передан)
                  value:
                    data:
                      currency: "BYN"
                      startDate: "2027-01-15T23:02:20Z"
                      startPrice: 0.0000
                      description: "dFqjjvMSPltGEKccDevaovyuMOSsOy"
                      bidIncrement: 0.1000
                      reservePrice: 0.1000
                      status: "ACTIVE"
                      endDate: "2028-07-07T19:21:33Z"
                      isPrivate: false
                      title: "yEpyzMKowD"
                      id: "b6893a4a-fdf9-4e1c-95fb-054d1906da7c"
                minimal:
                  summary: Только id и ownerName
                  value:
                    data:
                      id: "b6893a4a-fdf9-4e1c-95fb-054d1906da7c"
                      ownerName: "venik"
                full:
                  summary: Все поля включая allowedUsersCount (для приватного аукциона)
                  value:
                    data:
                      id: "b6893a4a-fdf9-4e1c-95fb-054d1906da7c"
                      title: "Закрытый аукцион"
                      description: "Только для приглашённых"
                      startPrice: 100.00
                      bidIncrement: 10.00
                      reservePrice: 200.00
                      isPrivate: true
                      status: "ACTIVE"
                      startDate: "2025-09-10T10:00:00Z"
                      endDate: "2025-09-15T18:00:00Z"
                      currency: "USD"
                      allowedUsersCount: 15
                      ownerName: "admin"
        '404':
          description: Сущность не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                status: 404
                error: "Entity not found"
                message: "Auction with id 123e4567-e89b-12d3-a456-426614174000 not found"
                path: "/auction/123e4567-e89b-12d3-a456-426614174000"
                timestamp: "2025-08-30T14:30:02Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                accessDenied:
                  summary: Пароль не указан или неверный
                  value:
                    status: 403
                    error: "Access denied"
                    message: "Password is required for private auction"
                    path: "/auction/123e4567-e89b-12d3-a456-426614174000"
                    timestamp: "2025-08-30T14:30:03Z"
                forbidden:
                  summary: Пользователь не имеет прав доступа
                  value:
                    status: 403
                    error: "Access denied"
                    message: "User not allowed to access this auction"
                    path: "/auction/123e4567-e89b-12d3-a456-426614174000"
                    timestamp: "2025-08-30T14:30:04Z"
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auction/getAll:
    get:
      tags:
        - Auctions
      summary: Получить список аукционов постранично
      description: |
        Возвращает список аукционов с постраничной навигацией.  
        Можно указать, какие поля включить в ответ через параметр **fields**.  

        Особенности:  
        1. Если `fields` не указан, то:  
           - для публичных возвращаются поля:  
             `bidIncrement, reservePrice, status, endDate, isPrivate, title, id, currency, startDate, startPrice, description`  
           - для приватных возвращаются поля:  
             `isPrivate, title, id, currency, startPrice, description`  

        2. Всего можно запросить поля:  
           `bidIncrement, reservePrice, status, endDate, isPrivate, title, id, currency, startDate, startPrice, description, ownerName, ownerId`  

        3. Для приватных аукционов возвращаются только:  
           `title, description, startPrice, isPrivate, id, currency`
      operationId: getAllAuctions
      parameters:
        - name: page
          in: query
          required: false
          description: Номер страницы (начиная с 0)
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          required: false
          description: Размер страницы (количество элементов на странице)
          schema:
            type: integer
            minimum: 1
            default: 5
        - name: fields
          in: query
          required: false
          description: Список полей, которые нужно включить в ответ
          schema:
            type: array
            items:
              type: string
              enum:
                - bidIncrement
                - reservePrice
                - status
                - endDate
                - isPrivate
                - title
                - id
                - currency
                - startDate
                - startPrice
                - description
                - ownerName
                - ownerId
      responses:
        '200':
          description: Успешный ответ с постраничным списком аукционов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResponse'
              example:
                data:
                  - title: "WawzcgSbNm"
                    description: "JWflKnMwxZYTDtgrumrghmzIPYDihY"
                    startPrice: 0.0000
                    isPrivate: false
                    id: "87912135-68b8-4b72-ba89-5c253d9e5606"
                    currency: "BYN"
                    ownerName: "venik"
                  - title: "WawzcgSbNm"
                    description: "JWflKnMwxZYTDtgrumrghmzIPYDihY"
                    startPrice: 0.0000
                    isPrivate: true
                    id: "1c2027b0-5964-43ad-ac12-660a2a192452"
                    currency: "BYN"
                pageNumber: 0
                pageSize: 5
                totalElements: 6
                totalPages: 2
                first: true
                last: false
                numberOfElements: 5
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Неавторизованный пользователь
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            status: 401
            error: "Unauthorized"
            message: "JWT token is missing or invalid"
            path: "/auction"
            timestamp: "2025-08-30T14:35:01Z"
    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            status: 500
            error: "Server error"
            message: "Unexpected exception"
            path: "/auction"
            timestamp: "2025-08-30T14:30:05Z"

  schemas:
    PagedResponse:
      type: object
      properties:
        data:
          type: array
          description: Список аукционов (набор полей зависит от параметра fields)
          items:
            type: object
            additionalProperties: true
        pageNumber:
          type: integer
          description: Номер текущей страницы
        pageSize:
          type: integer
          description: Размер страницы
        totalElements:
          type: integer
          description: Общее количество элементов
        totalPages:
          type: integer
          description: Общее количество страниц
        first:
          type: boolean
          description: Признак первой страницы
        last:
          type: boolean
          description: Признак последней страницы
        numberOfElements:
          type: integer
          description: Количество элементов на текущей странице
      required:
        - data
        - pageNumber
        - pageSize
        - totalElements
        - totalPages
        - first
        - last
        - numberOfElements
    ApiError:
      type: object
      properties:
        status:
          type: integer
          description: HTTP статус ошибки
        error:
          type: string
          description: Краткое описание ошибки
        message:
          type: string
          description: Подробное сообщение об ошибке
        path:
          type: string
          description: Путь запроса, на котором произошла ошибка
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
      required:
        - status
        - error
        - message
        - path
        - timestamp

    CreateAuction:
      type: object
      required:
        - title
        - description
        - startPrice
        - bidIncrement
        - reservePrice
        - isPrivate
        - startDate
        - endDate
        - currency
      properties:
        title:
          description: Заголовок аукциона, от 3 до 100 символов
          type: string
          minLength: 3
          maxLength: 100
        description:
          description: Подробное описание аукциона, минимум 10 символов
          type: string
          minLength: 10
        startPrice:
          description: Стартовая цена аукциона, не может быть отрицательной
          type: number
          format: float
          minimum: 0.0
        bidIncrement:
          description: Минимальный шаг ставки, не может быть меньше 0.1
          type: number
          format: float
          minimum: 0.1
        reservePrice:
          description: Резервная цена, ниже которой аукцион не будет продан
          type: number
          format: float
          minimum: 0.1
        isPrivate:
          description: Флаг приватного аукциона (true — приватный, false — публичный)
          type: boolean
        startDate:
          description: Дата и время начала аукциона, не может быть в прошлом
          type: string
          format: date-time
          example: "2025-08-30T14:14:02Z"
        endDate:
          description: Дата и время окончания аукциона, должна быть позже даты начала
          type: string
          format: date-time
          example: "2025-08-30T16:14:02Z"
        currency:
          description: Валюта аукциона
          type: string
          enum: [USD, EUR, RUB, BYN, GBP, CNY, JPY, CHF, AUD, CAD]

    CreatedAuction:
      type: object
      properties:
        id:
          description: Уникальный идентификатор созданного аукциона
          type: string
          format: uuid
        password:
          description: Сгенерированный пароль от аукциона. Для публичного аукциона может быть null
          type: string
          format: uuid
          nullable: true

    AuctionInfo:
      type: object
      properties:
        id:
          description: Уникальный идентификатор аукциона
          type: string
          format: uuid
        title:
          description: Заголовок аукциона
          type: string
        description:
          description: Подробное описание аукциона
          type: string
        startPrice:
          description: Стартовая цена
          type: number
          format: float
        bidIncrement:
          description: Минимальный шаг ставки
          type: number
          format: float
        reservePrice:
          description: Резервная цена аукциона
          type: number
          format: float
        ownerName:
          description: Имя создателя аукциона
          type: string
        allowedUsersCount:
          description: Количество участников для приватных аукционов
          type: integer
          nullable: true
        isPrivate:
          description: Флаг приватного аукциона
          type: boolean
        status:
          description: Статус аукциона
          type: string
          enum: [ACTIVE, INACTIVE, FINISHED]
        startDate:
          description: Дата и время начала аукциона
          type: string
          format: date-time
          example: "2025-08-30T14:14:02Z"
        endDate:
          description: Дата и время окончания аукциона
          type: string
          format: date-time
          example: "2025-08-30T16:14:02Z"
        currency:
          description: Валюта аукциона
          type: string
          enum: [USD, EUR, RUB, BYN, GBP, CNY, JPY, CHF, AUD, CAD]
      required:
        - id
        - title
        - description
        - startPrice
        - bidIncrement
        - reservePrice
        - isPrivate
        - status
        - startDate
        - endDate
        - currency
