server:
  port: 8080

settings:
  db:
    batch-size: 1000
  scheduler:
    finish:
      execute: true //Выполнять ли завершение закончившихся аукционов
      repeat-time-seconds: 15 //Как часто повторять (в секундах)
    deactivate:
      execute: true //Выполнять ли деактивацию бесполезных завершившихся аукционов
      repeat-time-seconds: 30 //Как часто повторять (в секундах)
    cleaner:
      execute: true //Чистить ли бесполезные аукционы
      repeat-time-seconds: 40 //Как часто повторять (в секундах)
    archiver:
      execute: true //Архивировать ли валидные завершившиеся аукционы
      repeat-time-days: 1 //Как часто повторять (в днях)

grpc:
  server:
    port: 5436
    security:
      enabled: true
      certificate-chain: classpath:certs/grpc/server-cert-example.pem
      private-key: classpath:certs/grpc/server-key-example.pem
  client:
    bid-service:
      address: localhost:5438
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/grpc/bid-cert-example.pem
    user-service:
      address: localhost:5435
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/grpc/auth-cert-example.pem

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  main:
    banner-mode: off

springdoc:
  swagger-ui:
    url: /openapi.yaml
