server:
  port: 8080

grpc:
  server:
    port: 5436
    security:
      enabled: true
      certificate-chain: classpath:certs/grpc/server-auction-cert-example.pem # замените на ваш cert
      private-key: classpath:certs/grpc/server-auction-key-example.pem        # замените на ваш key

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8086/.well-known/jwks.json # замените на ваш path to pub key
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name                  # имя БД
    username: your_db_user                                              # пользователь БД
    password: your_db_password                                          # пароль БД
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  main:
    banner-mode: off

springdoc:
  swagger-ui:
    url: /openapi.yaml

