server:
  port: 8081

grpc:
  client:
    auction-service:
      address: localhost:5434
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:client-truststore.jks
        trust-store:
          path: certs/client-truststore.jks
          type: JKS
          password: pass


spring:
  datasource:
    url: jdbc:postgresql://localhost:local_db_port/db_name
    password: db_password
    username: db_user
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
